config/routes.rb
Rails.application.routes.draw do

  get '/jobs?sort=location', to:'jobs#index'
  get '/dashboard', to: 'dashboards#index'
  resources :comments, only: [:create]

  resources :categories
  resources :companies do
    resources :jobs
    resources :contacts, only: [:create]
  end
  resources :jobs, only: [:index]

end

app/models/category.rb
class Category < ActiveRecord::Base
validates :title, uniqueness: true

has_many :jobs
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :job
end

app/models/company.rb
class Company < ActiveRecord::Base
  validates :name, :city, presence: true
  validates :name, uniqueness: true
  has_many :jobs
  has_many :contacts

  def show_top_three
    tre =
    Company.all.sort_by{|company| company.average_level_of_interest_score}.reverse[0..2]
    tre.map do |company|
      "#{company.name.capitalize} has an average level of interest of #{company.average_level_of_interest_score}"
    end
  end

  def average_level_of_interest_score
    jobs.average(:level_of_interest).to_f
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :company

  def full_name
    "#{first_name} #{last_name}" 
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :title, :level_of_interest, presence: true
  belongs_to :company
  belongs_to :category
  has_many :comments

  def show_by_count_of_jobs_by_level_of_interest
    count_to_jobs =
    Job.order(:level_of_interest).reverse.group_by {|job| job.level_of_interest}
    prepared = count_to_jobs.map do |level_of_interest,job|
      "There #{grammar_corrector(job)} with a level of interest of #{level_of_interest}."
    end
  end

  def grammar_corrector(job)
    return "is 1 job"              if job.count == 1
    "are #{job.count} jobs"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(category_id)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to category_path(@category)
    else
      redirect_to new_category_path
    end
  end

  def edit
    @category = Category.find(category_id)
  end

  def update
    @category = Category.find(category_id)
    @category.update_attributes(category_params)
    redirect_to categories_path
  end

  def destroy
    category = Category.find(category_id)
    category.delete
    redirect_to categories_path 
  end

  private

  def category_params
    params.require(:category).permit(:title)
  end

  def category_id
    params[:id]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    comment = Comment.create(comment_params)
    job = Job.find(comment.job_id)
    company = Company.find(job.company_id)
    redirect_to company_job_path(company, job)
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :job_id )
  end



end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    if include_location?
      @companies = Company.where(city: city)
      render :city
    elsif include_sort?
      @companies = Company.order(:city)
      render :jobs_by_location
    else
      @companies = Company.all
    end
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      flash[:success] = "#{@company.name} added!"
      redirect_to company_path(@company)
    else
      render :new
    end
  end

  def show
    @company = Company.find(params[:id])
    @contact = Contact.new
    # redirect_to company_jobs_path(company)
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    @company.update(company_params)
    if @company.save
      flash[:success] = "#{@company.name} updated!"
      redirect_to company_path(@company)
    else
      render :edit
    end
  end

  def destroy
    company = Company.find(params[:id])
    company.delete

    flash[:success] = "#{company.name} was successfully deleted!"
    redirect_to companies_path
  end


  private

  def company_params
    params.require(:company).permit(:name, :city)
  end

  def include_sort?
  true if params[:sort]
  end

  def city
    params[:location]
  end

  def include_location?
    true if params[:location]

  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def create
    contact = Contact.create(contact_params)
    company = Company.find contact.company_id
    redirect_to company_path company
  end

  private
  def contact_params
      params.require(:contact).permit(:first_name,:last_name,:position,:email,:company_id)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @company = Company.new
    @job = Job.new
    @companies = Company.pluck(:city).uniq
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    if include_sort?
      @jobs = Job.order(:level_of_interest).reverse
      render :sorted_jobs
    else
      @company = Company.find(company_id)
      @jobs = @company.jobs
    end
  end

  def new
    @categories = Category.all
    @company = Company.find(company_id)
    @job = Job.new()
  end

  def create
    category =
    @company = Company.find(company_id)
    @job = @company.jobs.new(job_params)
    if @job.save
      flash[:success] = "You created #{@job.title} at #{@company.name}"
      redirect_to company_job_path(@company, @job)
    else
      render :new
    end
  end

  def show
    @job = Job.find(job_id)
    @comment = Comment.new
  end

  def edit
    @categories = Category.all
    @company = Company.find(company_id)
    @job = Job.find(job_id)
  end

  def update
    @job = Job.find(job_id)
    @job.update_attributes(job_params)
    redirect_to company_job_path(company_id, job_id)
  end

  def destroy
    @job = Job.find(job_id)
    @job.destroy
    @company = Company.find(company_id)
    redirect_to company_jobs_path
  end

  private

  def job_id
    params[:id]
  end

  def company_id
    params[:company_id]
  end

  def category_id
    params.require(:job).permit(:category)[:category]
  end

  def job_params
    params.require(:job).permit(:title, :description, :level_of_interest, :category_id)
  end

  def include_sort?
  true if params[:sort]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>

  <%= f.label      :title %>
  <%= f.text_field :title %>

  <%= f.submit %>
<% end %>

app/views/categories/edit.html.erb
<h3> <%= "Edit Category #{@category.title}" %></h3>
<%= render partial: "form" %>

app/views/categories/index.html.erb
<h3>All Categories</h3>
<%= link_to "New Category", new_category_path %>
<ul>
  <% @categories.each do |category| %></ul>
    <li> <%= link_to category.title, category_path(category) %> <%= link_to "Edit", edit_category_path(category) %> <%= link_to "Delete", category_path(category), method: "delete" %>  </li>
    <% end %>
<ul>

app/views/categories/new.html.erb
<h3>Add Category</h3>
<%= render partial: "form" %>

app/views/categories/show.html.erb
<p class="text-center">

<h3><%= @category.title %></h3>
  <ul>
    <% @category.jobs.each do |job| %>
      <li><%= job.title %></li>
      <% end %>
  </ul>
<br>
<%= link_to "Edit", edit_category_path(@category) %>
</p>

app/views/companies/_contact_form.html.erb
<%= form_for [@company, @contact] do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <%= f.label :position %>
  <%= f.text_field :position %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.hidden_field :company_id, value: @company.id %>
  <%= f.submit %>
<% end %>

app/views/companies/_form.html.erb
<%= form_for @company do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.submit %>
<% end %>

app/views/companies/city.html.erb
<h3>Jobs in <%= @companies.first.city %> </h3>

<% @companies.each do |company| %>
  <ul class=company_<%= company.id %>>
    <%= link_to company.name, company_path(company) %> - <%= company.city %><br>
    <%= link_to "Edit", edit_company_path(company) %>
    <%= link_to "Delete", company_path(company), method: "delete" %>
  </ul>
<% end %>

<h4>Job Count: <%= @companies.reduce(0){|total, company| total+company.jobs.count} %> </h4>

app/views/companies/edit.html.erb
<h2>Edit <%= @company.name %> here!</h2>

<%= render partial: "form" %>

app/views/companies/index.html.erb
<h3>All Companies</h3>

<% @companies.each do |company| %>
  <ul class=company_<%= company.id %>>
    <%= link_to company.name, company_path(company) %> - <%= company.city %><br>
    <%= link_to "Edit", edit_company_path(company) %>
    <%= link_to "Delete", company_path(company), method: "delete" %>
  </ul>
<% end %>

app/views/companies/jobs_by_location.html.erb
<h3>All Jobs by Location</h3>

<ul>
  <% @companies.each do |company| %>
    <li>  <%= company.name %></li>
    <ul>
      <% company.jobs.each do |job| %>
        <li> <%=job.title %> </li>
      <% end %>
    </ul>
  <% end %>
</ul>

app/views/companies/new.html.erb
<h2>Create a new company here!</h2>

<%= render partial: "form" %>

app/views/companies/show.html.erb
Jobs for <strong><%= @company.name %></strong>

<% @company.jobs.each do |job| %>
  <ul><%= link_to job.title, company_job_path(@company, job) %> at <%= job.company.name %></ul>
<% end %>

Contacts for <strong><%= @company.name %></strong>


<ul>
  <% @company.contacts.reverse.each do |contact| %>
  <li><%= contact.full_name%></li>
  <li><%= contact.position%></li>
  <li><%= contact.email%></li>
  <br>
  <% end %>
</ul>

<%= render partial: "contact_form" %>

app/views/dashboards/index.html.erb
<div class="row">
  <div class="col-md-4">

  <h3>Top Three Companies By Average level of interest</h3>

  <ol>
    <% @company.show_top_three.each do |line| %>
    <li> <%=line%></li>
    <% end %>
  </ol>
</div>

  <div class="col-md-4">
    <h3>Amount of jobs by Level of interest</h3>

    <ul>
      <%@job.show_by_count_of_jobs_by_level_of_interest.each do |line| %>
      <li><%=line%></li>
      <% end %>
  </ul>
  </div>

  <div class="col-md-4">
    <h3>Count of Jobs by Location</h3>
    <ul>
      <% @companies.each do |name| %>
      <li> <%=link_to name, "#{companies_path}?location=#{name}" %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/jobs/_comment_form.html.erb
<h5>New Comment</h5>
<%= form_for @comment do |f| %>
<h5>Comment</h5>
<%= f.label :content %>
<%= f.text_area :content %>
<%= f.hidden_field :job_id, value: @job.id %>
<%= f.submit %>
<% end %>

app/views/jobs/_comment_show.html.erb
<h4>Comments</h4>
<ul>
  <% @job.comments.reverse.each do |comment| %>
  <li><%= comment.content%> </li>
  <% end %>
</ul>

app/views/jobs/_form.html.erb
<%= form_for [@company, @job] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :level_of_interest %>
  <%= f.number_field :level_of_interest %>

  <%= f.label :category %>
  <%= f.collection_select :category_id, @categories, :id, :title, include_blank: true %>

  <%= f.submit %>
<% end %>

<%= link_to "Add Category", new_category_path %>

app/views/jobs/edit.html.erb
<h3> Edit  <%="#{@job.title} at  #{@job.company.name}" %></h3>
<%= render partial: "form" %>

app/views/jobs/index.html.erb
All Jobs for <strong><%= @company.name %></strong>

<% @jobs.each do |job| %>
  <ul><%= link_to job.title, company_job_path(@company, job) %> at <%= job.company.name %></ul>
<% end %>

app/views/jobs/new.html.erb
<h2>Create a new job at <%= @company.name %> here!</h2>

<%= render partial: "form" %>

app/views/jobs/show.html.erb
Title: <%= @job.title %>
<br>

Description: <%= @job.description %>
<br>

Level of Interest: <%= @job.level_of_interest %>
<br>
Category : <%=@job.category.title  %>
<br>

Company: <%= link_to @job.company.name, company_path(@job.company) %>
<br>


<%= link_to "Update",  edit_company_job_path(@job.company, @job) %>
<br>
<%= link_to "Delete", company_job_path(@job.company, @job), method: :delete %>

<%= render partial: "comment_show" %>

<%= render partial: "comment_form" %>

app/views/jobs/sorted_jobs.html.erb
<h3>Jobs by level of interest rating</h3>


<ul>
  <% @jobs.each do |job| %>
  <li> <%="#{job.title} with #{job.level_of_interest} level of interest rating." %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: name %>
  <% end %>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href= <%= "#{dashboard_path}" %>>Dashboard</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"> <%= link_to "Companies", companies_path%>      </li>
        <li class="active"> <%= link_to "Add Company", new_company_path%></li>

      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to "Categories", categories_path%> </li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="container">

<%= yield %>
</div>

</body>
</html>